services:
  parabank-tests:
    image: ievjai/parabank-tests:latest
    volumes:
      - ./reports:/app/reports
      - ./allure-results:/app/allure-results
    environment:
      - BASE_URL=https://parabank.parasoft.com
      - CI=true
    command: pnpm run test:ui

  allure-report:
    image: ievjai/parabank-tests:latest
    command: pnpm run report
    ports:
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
    depends_on:
      parabank-tests:
        condition: service_completed_successfully

networks:
  default:
    driver: bridge 