version: '3.8'

services:
  parabank-tests:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../reports:/app/reports
      - ../allure-results:/app/allure-results
    environment:
      - BASE_URL=https://parabank.parasoft.com
      - CI=true
    networks:
      - test-network

  allure-server:
    image: frankescobar/allure-docker-service
    ports:
      - "5050:5050"
    volumes:
      - ../allure-results:/app/allure-results
      - ../allure-reports:/app/default-reports
    networks:
      - test-network

networks:
  test-network:
    driver: bridge 